name: Provision Github Runners

on:
  workflow_dispatch:
    inputs:
      owner:
        description: The account owner of the repository. The name is not case sensitive
        required: true
        default: d-user11
      repo:
        description: The name of the repository without the .git extension. The name is not case sensitive.
        required: true
        default: gh-self-hosted-runners

jobs:
  provision-runner:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: |
          terraform plan -input=false -no-color -detailed-exitcode -out tf.plan \
            -var owner=${{ github.event.inputs.owner }} \
            -var repo=${{ github.event.inputs.repo }} \
            -var access_token=

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Manual approval before apply
        uses: trstringer/manual-approval@v1
        if: steps.plan.outputs.exitcode == 2 # Has changes 
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ env.APPROVERS }}
          minimum-approvals: 1
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          issue-title: Manual Approval Required for Terraform Apply
          issue-body: Please approve or deny the deployment.

      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == 2 # Has changes
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tf.plan